### ISSUE TITLE
This package now throws peer dependency warnings with Node LTS versions, as of the eslint-plugin-prettier release version 4.0

### ISSUE THREAD

**Issue by trackleft** [shaundrong/eslint-config-drupal-bundle#4]
On LTS version of node 14.17.6 (includes npm 6.14.15) https://nodejs.org/en/download/
eslint-plugin-prettier released version 4.0 https://github.com/prettier/eslint-plugin-prettier/releases

Due to npm versions 3-6 not downloading peer dependencies automatically. 

We see the following errors / warnings

```
npm WARN eslint-plugin-prettier@4.0.0 requires a peer of eslint@>=7.28.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-prettier@4.0.0 requires a peer of prettier@>=2.0.0 but none is installed. You must install peer dependencies yourself.
```

The most recent version of this package sets dependencies to these versions.

    "eslint": "^4.19.1",
    "prettier": "^1.14.0"

**Comment by trackleft** [comment]
Should we add 
`"eslint-plugin-prettier": "~3"` to dependencies?

**Comment by trackleft** [comment]
eslint-plugin-prettier v4 no longer supports eslint 4, 5, or 6 , along with support being dropped for prettier v1 according to this https://github.com/prettier/eslint-plugin-prettier/commit/acb56f3b2891b2a6998a75a7d4406183d452ba16

So we could also drop support for those in this repo, but that sounds more scary than the previously suggested fix.

**Comment by shaundrong** [comment]
Thanks @trackleft not sure I want to move past what Drupal(9) core is using just to be safe, but I've included your suggestion
> Should we add
> `"eslint-plugin-prettier": "~3"` to dependencies?

along with some other updates For Drupal 9. I think @theodoreb is looking to make [eslint-config-drupal](https://github.com/theodoreb/eslint-config-drupal) the suggested default on Drupal.org which fine with me as I just made this to replace the old default before prettier was added in Drupal 8.6.

**Comment by shaundrong** [comment]
Update dependency in #5
